version: "3.4"

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "DotProject@2023"
            ACCEPT_EULA: "Y"
    api:
        image: ${DOCKER_REGISTRY-}dotproject:v1
        build:
          context: .
          dockerfile: ./DotProject.Services.Api/Dockerfile
        ports:
          - "8081:80"
          - "8082:443"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=DotProject@2023
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockerdemo.pfx
        volumes:
          - ~/.aspnet/https:/https:ro
        depends_on:
          - db
    